export interface InterfaceSendDataSparePart {
    action : number,
    id : number,
    namaSparepart : string,
    kodeSparepart : string,
    grupSparepart : number,
    grupKodeAHM : number,
    namaLokal : string,
    uom : string,
    hargaJual : number,
    rak : string,
    barcode : string,
    hargaClaimOli : number,
    catatan : string,
    tipeKomisi : number,
    satuanKomisi : number,
    nilaiKomisi : number,
    aktif : boolean,
}
