name: Next.js CI/CD

on:
  push:
    branches: [ canary-v0.0.1 ] # Mengubah branch target menjadi main atau sesuaikan dengan branch yang Anda gunakan
  pull_request:
    branches: [ canary-v0.0.1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.11.0' # Spesifikasi versi Node.js
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build # Memastikan Anda memiliki script "build" di package.json

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/nextjs-app:canary-v0.0.1
          docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-app:canary-v0.0.1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:canary-v0.0.1
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            # Menggunakan port 8081 untuk aplikasi Next.js
            docker run -d --name nextjs-app -p 8081:3000 ${{ secrets.DOCKER_USERNAME }}/nextjs-app:canary-v0.0.1
